version: "3.8"
services:
  # Django server with built in SQLite3 database
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: class-booking-django-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
