# Generated by Django 5.2.4 on 2025-07-06 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('class_type', models.CharField(choices=[('yoga', 'Yoga'), ('zumba', 'Zumba'), ('hiit', 'HIIT')], default='yoga', max_length=10)),
                ('class_time', models.DateTimeField()),
                ('instructor_name', models.CharField(max_length=100)),
                ('instructor_email', models.EmailField(max_length=200)),
                ('max_slots', models.PositiveIntegerField(help_text='Total number of seats/clients class can accomodate.')),
                ('available_slots', models.PositiveIntegerField(help_text='Total number of available/unbooked seats.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FitnessClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=200)),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.fitnessclass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
